version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    container_name: front-youtube-app
    volumes: 
      - ".:/app"
    ports:
      - "3001:3000"
    tty: true